
package librarysystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

public class aboutSystem extends javax.swing.JFrame {

    public aboutSystem() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        closeBTN = new javax.swing.JLabel();
        bgg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/66.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, 170));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 23, 23));
        jLabel5.setText("NEPOMUCENO, Francis Florez ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 360, 60));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 23, 23));
        jLabel7.setText("MARTICIO, Yvonnie");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 250, 60));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 23, 23));
        jLabel6.setText("This system was designed and built by Group 1.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 630, 50));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 23, 23));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 720, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/red.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 790, 10));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 23, 23));
        jLabel8.setText("JAVIER, Ronan ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 210, 60));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 23, 23));
        jLabel9.setText("FREDERICK, Harvey ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 250, 60));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 23, 23));
        jLabel10.setText("ELEAZAR, Angelica ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 240, 60));

        jLabel12.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 23, 23));
        jLabel12.setText("BATOON, Christian Jei");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 290, 60));

        jLabel13.setFont(new java.awt.Font("Dubai", 0, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(27, 23, 23));
        jLabel13.setText("MAGPOC, John Paul");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 250, 60));

        closeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ekis.png"))); // NOI18N
        closeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTNMouseClicked(evt);
            }
        });
        jPanel1.add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 40, 50));

        bgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/111.png"))); // NOI18N
        jPanel1.add(bgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1130, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTNMouseClicked
    this.dispose();
    }//GEN-LAST:event_closeBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgg;
    private javax.swing.JLabel closeBTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
