package librarysystem;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import static librarysystem.Admin_Module.dateNgayonField;
import static librarysystem.User_Module.dateNgayonFieldUSER;
//import static librarysystem.Admin_Module.monthngayon;
//import static librarysystem.Admin_Module.yearngayon;

public class LoginPage extends javax.swing.JFrame {
    Connection con = connectLibrary.connecting();
    ResultSet rs;
    PreparedStatement pst;
    CardLayout cardLayout;
    int AdminAttempt = 1;
    int UserAttempt = 1;
    public LoginPage() {
        initComponents();
        connectLibrary.connecting();
        cardLayout = (CardLayout)(CARD.getLayout());
        cardLayout.show(CARD, "LoginPagePANEL");
    }
    private void displayDateToday (){
        java.util.Date date = new java.util.Date();
        LocalDate dateToday = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dateTodayIs = dateToday;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMM d, yyyy");
        String todayIs = dateTodayIs.format(formatter);
        dateNgayonField.setText(todayIs);
    }
    private void displayDateTodayUSER (){
        java.util.Date date = new java.util.Date();
        LocalDate dateToday = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dateTodayIs = dateToday;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMM d, yyyy");
        String todayIs = dateTodayIs.format(formatter);
        dateNgayonFieldUSER.setText(todayIs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CARD = new javax.swing.JPanel();
        LoginPagePANEL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ADMINBTN = new javax.swing.JLabel();
        USERBTN = new javax.swing.JLabel();
        LoginAdminPANEL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ADMINNUMBER = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ADMINPASSWORD = new javax.swing.JPasswordField();
        signINBTN = new javax.swing.JLabel();
        ADMINSHOWPASS = new javax.swing.JCheckBox();
        ADMINERRORMSG = new javax.swing.JLabel();
        BACKBTN = new javax.swing.JLabel();
        LoginUserPANEL = new javax.swing.JPanel();
        BACKBTN1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        USERSIGNINBTN = new javax.swing.JLabel();
        USERNUMBER = new javax.swing.JTextField();
        USERPASSWORD = new javax.swing.JPasswordField();
        USERSHOWPASS = new javax.swing.JCheckBox();
        userERROMSG = new javax.swing.JLabel();
        rulesSystemBTN = new javax.swing.JLabel();
        systemAbout = new javax.swing.JLabel();
        BBBBBBBBBGGGGGGGG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/Books.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 90, 100));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 23, 23));
        jLabel3.setText("Library Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 330, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/red.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 340, 10));

        CARD.setLayout(new java.awt.CardLayout());

        LoginPagePANEL.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        jLabel4.setText("Login As");

        ADMINBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/1.png"))); // NOI18N
        ADMINBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADMINBTNMouseClicked(evt);
            }
        });

        USERBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/22.png"))); // NOI18N
        USERBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USERBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPagePANELLayout = new javax.swing.GroupLayout(LoginPagePANEL);
        LoginPagePANEL.setLayout(LoginPagePANELLayout);
        LoginPagePANELLayout.setHorizontalGroup(
            LoginPagePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPagePANELLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(167, 167, 167))
            .addGroup(LoginPagePANELLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(LoginPagePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADMINBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USERBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPagePANELLayout.setVerticalGroup(
            LoginPagePANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPagePANELLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ADMINBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(USERBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        CARD.add(LoginPagePANEL, "LoginPagePANEL");

        LoginAdminPANEL.setBackground(new java.awt.Color(255, 255, 255));
        LoginAdminPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel5.setText("ADMIN LOGIN");
        LoginAdminPANEL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 40));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel6.setText("ID Number");
        LoginAdminPANEL.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        ADMINNUMBER.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ADMINNUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ADMINNUMBERKeyPressed(evt);
            }
        });
        LoginAdminPANEL.add(ADMINNUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 40));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel7.setText("Password");
        LoginAdminPANEL.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        ADMINPASSWORD.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ADMINPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ADMINPASSWORDKeyPressed(evt);
            }
        });
        LoginAdminPANEL.add(ADMINPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 370, 40));

        signINBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/signin.png"))); // NOI18N
        signINBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signINBTNMouseClicked(evt);
            }
        });
        LoginAdminPANEL.add(signINBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 50));

        ADMINSHOWPASS.setBackground(new java.awt.Color(255, 255, 255));
        ADMINSHOWPASS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ADMINSHOWPASS.setText("Show Password");
        ADMINSHOWPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINSHOWPASSActionPerformed(evt);
            }
        });
        LoginAdminPANEL.add(ADMINSHOWPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 30));

        ADMINERRORMSG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ADMINERRORMSG.setForeground(new java.awt.Color(204, 0, 0));
        LoginAdminPANEL.add(ADMINERRORMSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, 30));

        BACKBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/re10.png"))); // NOI18N
        BACKBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBTNMouseClicked(evt);
            }
        });
        LoginAdminPANEL.add(BACKBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 120, 50));

        CARD.add(LoginAdminPANEL, "LoginAdminPANEL");

        LoginUserPANEL.setBackground(new java.awt.Color(255, 255, 255));
        LoginUserPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACKBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/re10.png"))); // NOI18N
        BACKBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBTN1MouseClicked(evt);
            }
        });
        LoginUserPANEL.add(BACKBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 110, 50));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel8.setText("ID Number");
        LoginUserPANEL.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel9.setText("Password");
        LoginUserPANEL.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setText("USER LOGIN");
        LoginUserPANEL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 170, 40));

        USERSIGNINBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/signin.png"))); // NOI18N
        USERSIGNINBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USERSIGNINBTNMouseClicked(evt);
            }
        });
        LoginUserPANEL.add(USERSIGNINBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 50));

        USERNUMBER.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        USERNUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERNUMBERKeyPressed(evt);
            }
        });
        LoginUserPANEL.add(USERNUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 40));

        USERPASSWORD.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        USERPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERPASSWORDKeyPressed(evt);
            }
        });
        LoginUserPANEL.add(USERPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 370, 40));

        USERSHOWPASS.setBackground(new java.awt.Color(255, 255, 255));
        USERSHOWPASS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        USERSHOWPASS.setText("Show Password");
        USERSHOWPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERSHOWPASSActionPerformed(evt);
            }
        });
        LoginUserPANEL.add(USERSHOWPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 129, 29));

        userERROMSG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userERROMSG.setForeground(new java.awt.Color(204, 0, 0));
        LoginUserPANEL.add(userERROMSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, 30));

        CARD.add(LoginUserPANEL, "LoginUserPANEL");

        jPanel1.add(CARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 420, 390));

        rulesSystemBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/help1.png"))); // NOI18N
        rulesSystemBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rulesSystemBTNMouseClicked(evt);
            }
        });
        jPanel1.add(rulesSystemBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, 40, 40));

        systemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/info.png"))); // NOI18N
        systemAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                systemAboutMouseClicked(evt);
            }
        });
        jPanel1.add(systemAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 250, 40, 40));

        BBBBBBBBBGGGGGGGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/login1.png"))); // NOI18N
        jPanel1.add(BBBBBBBBBGGGGGGGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADMINBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADMINBTNMouseClicked
    cardLayout.show(CARD, "LoginAdminPANEL");
    }//GEN-LAST:event_ADMINBTNMouseClicked

    private void USERBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERBTNMouseClicked
    cardLayout.show(CARD, "LoginUserPANEL");
    }//GEN-LAST:event_USERBTNMouseClicked

    private void BACKBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN1MouseClicked
    cardLayout.show(CARD, "LoginPagePANEL");
    }//GEN-LAST:event_BACKBTN1MouseClicked

    private void ADMINPASSWORDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADMINPASSWORDKeyPressed
    String password=new String (ADMINPASSWORD.getPassword());
    signINBTN.setEnabled(true);
    }//GEN-LAST:event_ADMINPASSWORDKeyPressed

    private void ADMINSHOWPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINSHOWPASSActionPerformed
        if (ADMINSHOWPASS.isSelected()) {
            ADMINPASSWORD.setEchoChar((char)0);
        }else
        {
            ADMINPASSWORD.setEchoChar('*');
        }
    }//GEN-LAST:event_ADMINSHOWPASSActionPerformed

    private void USERNUMBERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNUMBERKeyPressed
    try{
        int i=Integer.parseInt(USERNUMBER.getText());
        userERROMSG.setText(" ");
        USERPASSWORD.setEnabled(true);
    }catch(NumberFormatException e){
        userERROMSG.setText("Please enter numbers only.");
        USERPASSWORD.setEnabled(false);
        //USERSIGNINBTN.setEnabled(false);
    }
    }//GEN-LAST:event_USERNUMBERKeyPressed

    private void USERPASSWORDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERPASSWORDKeyPressed
        String password=new String (USERPASSWORD.getPassword());
        USERSIGNINBTN.setEnabled(true);
    }//GEN-LAST:event_USERPASSWORDKeyPressed

    private void USERSHOWPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERSHOWPASSActionPerformed
        if (USERSHOWPASS.isSelected()) {
            USERPASSWORD.setEchoChar((char)0);
        }else{
            USERPASSWORD.setEchoChar('*');
        }
    }//GEN-LAST:event_USERSHOWPASSActionPerformed

    private void ADMINNUMBERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADMINNUMBERKeyPressed
    try{
        int i=Integer.parseInt(ADMINNUMBER.getText());
        ADMINERRORMSG.setText(" ");
        ADMINPASSWORD.setEnabled(true);
    }catch(NumberFormatException e){
        ADMINERRORMSG.setText("Please enter numbers only.");
        ADMINPASSWORD.setEnabled(false);
        //signINBTN.setEnabled(false);
    }
    }//GEN-LAST:event_ADMINNUMBERKeyPressed

    private void signINBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signINBTNMouseClicked
    if (ADMINNUMBER.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter your Username and Password first!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        return;
    }  if (ADMINPASSWORD.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter your Username and Password first!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        return; 
    
    }
    
    try{ 
        //con = DriverManager.getConnection("jdbc:derby://localhost:1527/LibraryManagementSystem", "group1", "librarysystem");
        String adminLogIn = "SELECT * FROM adminaccounts WHERE idnumber=? AND password=?";
        pst = con.prepareStatement(adminLogIn);
        String adminnum = ADMINNUMBER.getText();
        String adminpass = ADMINPASSWORD.getText();
        pst.setString(1, adminnum);
        pst.setString(2, adminpass);
        rs = pst.executeQuery();        
        if (rs.next() && AdminAttempt <=4){
            JOptionPane.showMessageDialog(null, "Admin Successful Login!");
            String id = ADMINNUMBER.getText();
            String name = rs.getString("FIRSTNAME");
            String bday = rs.getString("BIRTHDATE");
            new Admin_Module(id, name, bday).setVisible(true);
            displayDateToday ();
            this.dispose();
        } else if (AdminAttempt !=4){
            ADMINERRORMSG.setText("Incorrect Username or Password.");
            ADMINNUMBER.setText(null);
            ADMINPASSWORD.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "Please ask the Admin to reset your password. Thank you.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            ADMINNUMBER.setEnabled(false);
            ADMINPASSWORD.setEnabled(false);
            signINBTN.setEnabled(false);
            ADMINNUMBER.setText(null);
            ADMINPASSWORD.setText(null);
           // home.setEnabled(false);
            ADMINSHOWPASS.setEnabled(false);
            System.exit(0);
        }
        AdminAttempt++;
    }catch (Exception e){
     e.printStackTrace();
 }
    }//GEN-LAST:event_signINBTNMouseClicked

    private void USERSIGNINBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERSIGNINBTNMouseClicked
    if (USERNUMBER.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter your Username and Password first!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        return;
    }if (USERPASSWORD.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter your Username and Password first!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try{ 
        //con = DriverManager.getConnection("jdbc:derby://localhost:1527/LibraryManagementSystem", "group1", "librarysystem");
        String adminLogIn = "SELECT * FROM useraccounts WHERE idnumber=? AND password=?";
        pst = con.prepareStatement(adminLogIn);
        String adminnum = USERNUMBER.getText();
        String adminpass = USERPASSWORD.getText();

        pst.setString(1, adminnum);
        pst.setString(2, adminpass);
        rs = pst.executeQuery();         
        if (rs.next() && UserAttempt <=4){
            JOptionPane.showMessageDialog(null, "User Successful Login!");
            String id = USERNUMBER.getText();
            String name = rs.getString("FIRSTNAME");
            String bday = rs.getString("BIRTHDATE");
            String course = rs.getString("COURSE");
            String roleType =  rs.getString("MEMBERTYPE");
            new User_Module(id, name, bday, course, roleType).setVisible(true);
            displayDateTodayUSER();
            this.dispose();
        } else if (UserAttempt !=4){
            userERROMSG.setText("Incorrect username or password.");
            USERNUMBER.setText(null);
            USERPASSWORD.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "Please ask the Admin to reset your password. Thank you.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            USERNUMBER.setEnabled(false);
            USERNUMBER.setText(null);
            USERPASSWORD.setText(null);
            USERPASSWORD.setEnabled(false);
            USERSIGNINBTN.setEnabled(false);
            //home.setEnabled(false);
            USERSHOWPASS.setEnabled(false);
            System.exit(0);
        }   
        UserAttempt++;
    }catch (Exception e){
     e.printStackTrace();
 }
    }//GEN-LAST:event_USERSIGNINBTNMouseClicked

    private void BACKBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTNMouseClicked
    cardLayout.show(CARD, "LoginPagePANEL");
    }//GEN-LAST:event_BACKBTNMouseClicked

    private void systemAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemAboutMouseClicked
    aboutSystem about = new aboutSystem();
    about.setVisible(true);
    }//GEN-LAST:event_systemAboutMouseClicked

    private void rulesSystemBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rulesSystemBTNMouseClicked
    rulesSystem rules = new rulesSystem();
    rules.setVisible(true);
    }//GEN-LAST:event_rulesSystemBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMINBTN;
    private javax.swing.JLabel ADMINERRORMSG;
    private javax.swing.JTextField ADMINNUMBER;
    private javax.swing.JPasswordField ADMINPASSWORD;
    private javax.swing.JCheckBox ADMINSHOWPASS;
    private javax.swing.JLabel BACKBTN;
    private javax.swing.JLabel BACKBTN1;
    private javax.swing.JLabel BBBBBBBBBGGGGGGGG;
    private javax.swing.JPanel CARD;
    private javax.swing.JPanel LoginAdminPANEL;
    private javax.swing.JPanel LoginPagePANEL;
    private javax.swing.JPanel LoginUserPANEL;
    private javax.swing.JLabel USERBTN;
    private javax.swing.JTextField USERNUMBER;
    private javax.swing.JPasswordField USERPASSWORD;
    private javax.swing.JCheckBox USERSHOWPASS;
    private javax.swing.JLabel USERSIGNINBTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rulesSystemBTN;
    private javax.swing.JLabel signINBTN;
    private javax.swing.JLabel systemAbout;
    private javax.swing.JLabel userERROMSG;
    // End of variables declaration//GEN-END:variables
}
