
package librarysystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;


public class rulesSystem extends javax.swing.JFrame {

    public rulesSystem() {
        this.setUndecorated(true);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closeBTN = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bgg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1140, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 656));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, 50));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 43)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 23, 23));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM RULES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 810, 50));

        jLabel24.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(27, 23, 23));
        jLabel24.setText("account under the 'User Login'.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 260, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/66.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, 170));

        closeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ekis.png"))); // NOI18N
        closeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTNMouseClicked(evt);
            }
        });
        jPanel1.add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 40, 50));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 23, 23));
        jLabel6.setText("Each users has their own different windows for accessing their account.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 580, 50));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 23, 23));
        jLabel8.setText("Same goes for the Students and Faculty, they can only access their");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 600, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/red.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 810, 10));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 23, 23));
        jLabel9.setText("Admins can only access their account under the 'Admin Login'.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 640, 50));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 23, 23));
        jLabel10.setText("Admins and Users can only have four attempts to try to open their account ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 620, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 23, 23));
        jLabel12.setText("If it goes beyond four attempts, the system will tell you to directly go to the Librarian ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 700, 50));

        jLabel13.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(27, 23, 23));
        jLabel13.setText("if ever forgotten their ID Number or Password. ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 580, 50));

        jLabel14.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(27, 23, 23));
        jLabel14.setText("Students are only allowed to borrow 3 books. ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 620, 50));

        jLabel15.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(27, 23, 23));
        jLabel15.setText("for Faculties, they are allowed to borrow a book for 1 semester or 150 days.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 620, 50));

        jLabel16.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(27, 23, 23));
        jLabel16.setText("to reset your password and after that the system will automatically close.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 630, 50));

        jLabel17.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(27, 23, 23));
        jLabel17.setText("Each users are required to return their borrowed book before their due date");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 620, 50));

        jLabel18.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(27, 23, 23));
        jLabel18.setText("or else they will have a pending balance on their account. ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 620, 50));

        jLabel19.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(27, 23, 23));
        jLabel19.setText("Both Users are not allowed to borrow the same book.");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 620, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 50, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 50, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 50, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 50, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 50, 50));

        jLabel23.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(27, 23, 23));
        jLabel23.setText("Faculties are not limited to borrow the number of books.");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 620, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/ARROW1.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 50, 50));

        jLabel26.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(27, 23, 23));
        jLabel26.setText("The duration of borrowing a book for Students is only seven days while  ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 620, 50));

        bgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystem/last.png"))); // NOI18N
        jPanel1.add(bgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1130, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 1160, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTNMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rulesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rulesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rulesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rulesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rulesSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgg;
    private javax.swing.JLabel closeBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
